### ISSUE TITLE
Access (Read & write) required for civil project folder to Mr. Saravanan (3526)

### ISSUE THREAD

**Issue by praveen-isgec** [Isgec/ITIL-FileServer-Permissions#10]
Please provide me the Access (Read & write ) for “Civil projects” folder. 
Regards,
SARAVANAN 
EPC ENGG. (CIVIL) 

@Isgec/dc-infra-team  , Myself Praveen Kumar is working for the same.

**Comment by msrawat-isgec** [comment]
From: praveen-isgec ***@***.*** 
Sent: 18 March 2021 11:55
To: Isgec/ITIL-FileServer-Permissions
Cc: M. S. Rawat; Team mention
Subject: [Isgec/ITIL-FileServer-Permissions] Access (Read & write) required for civil project folder to Mr. Saravanan (3526) (#10)

 

Please provide me the Access (Read & write ) for “Civil projects” folder.
Regards,
SARAVANAN
EPC ENGG. (CIVIL)

@Isgec/dc-infra-team <https://github.com/orgs/Isgec/teams/dc-infra-team>  , Myself Praveen Kumar is working for the same.

**Comment by praveen-isgec** [comment]
Dear Mr. Saravanan,

 

I hope now you are able to access EPCPROJECTS data as per given details.

 

If you have any additional questions or concerns you would like us to
address, or require any further assistance, please let us know.

Regards.....

Praveen (SYSTEMS)



A-8, Sector- 63, Noida, UP

Email: ***@***.***

website: www.isgec.com

Mobile:  +91 8448595785

 

From: ***@***.***
***@***.***> On Behalf Of saravanan
Sent: 17 March 2021 14:49
To: 'Praveen Kumar' ***@***.***>
Cc: ***@***.***; 'vinay sharma' ***@***.***>;
'Helpdesk.chennai' ***@***.***>
Subject: RE: Access (Read & write) required for civil project folder

 

Dear sir,

 

Still I am not able to access the folder. Please do the needful.

 

Regards,

 

saravanan

 

 

From: Praveen Kumar ***@***.*** 
Sent: 03 February 2021 13:23
To: 'saravanan'
Cc: ***@***.*** ***@***.***> ; 'vinay
sharma'; 'Helpdesk.chennai'
Subject: RE: Access (Read & write) required for civil project folder

 

Dear Mr. Saravanan,

 

Needful is done as per given details. Please check .

 

If you have any additional questions or concerns you would like us to
address, or require any further assistance, please let us know.

Regards.....

Praveen (SYSTEMS)



A-8, Sector- 63, Noida, UP

Email: ***@***.*** ***@***.***> 

website: www.isgec.com <http://www.isgec.com> 

Mobile:  +91 8448595785

 

From: saravanan ***@***.***
***@***.***>  
Sent: 29 January 2021 12:16
To: 'Praveen Kumar'
Cc: ***@***.*** ***@***.***> 
Subject: FW: Access (Read & write) required for civil project folder

 

Dear sir,

 

Still the permission is not given. Please do the needful.

 

Regards,

 

saravanan

 

From: Premkumar ***@***.*** 
Sent: 19 January 2021 18:09
To: 'Praveen Kumar'
Cc: 'saravanan'
Subject: RE: Access (Read & write) required for civil project folder

 

Dear Praveen,

 

Please note that Read access can be given to all projects and Read & Write
access can be given to (KPCL,karnal,Antony lara,Green Atom, Kudgi &
Gadarwara)

 

Regards,

Premkumar

 

From: Praveen Kumar ***@***.***
***@***.***>  
Sent: 19 January 2021 16:52
To: ***@***.*** ***@***.***> 
Cc: 'saravanan'
Subject: RE: Access (Read & write) required for civil project folder

 

Dear Sir,

 

Mr. Saravanan wants  (Read / Write ) both permissions on whole
"CIVILPROJECTS" drive.

 

We required your approval. Kindly approve.

 

If you have any additional questions or concerns you would like us to
address, or require any further assistance, please let us know.

Regards.....

Praveen (SYSTEMS)



A-8, Sector- 63, Noida, UP

Email:  ***@***.***> ***@***.***

website:  <http://www.isgec.com> www.isgec.com

Mobile:  +91 8448595785

 

From: saravanan  ***@***.***>
***@***.*** 
Sent: 19 January 2021 16:44
To: 'Praveen Kumar'
Cc:  ***@***.***> ***@***.***
Subject: RE: Access (Read & write) required for civil project folder

 

Please do the needful at the earliest.

 

Regards,

 

SARAVANAN 

 

From: saravanan [ ***@***.***>
***@***.*** 
Sent: 18 January 2021 17:40
To: 'Praveen Kumar'
Cc: ***@***.***'
Subject: RE: Access (Read & write) required for civil project folder

 

Dear sir,

 

Access permissions required for all projects folders.

 

Regards,

 

SARAVANAN 

 

From: Praveen Kumar  ***@***.***>
***@***.*** 
Sent: 18 January 2021 17:34
To: 'saravanan'
Cc:  ***@***.***> ***@***.***
Subject: RE: Access (Read & write) required for civil project folder

 

Dear Saravanan,

 

Please share the projects folders name on which you want to access
permissions also we required HOD approval for the same.

 

 

If you have any additional questions or concerns you would like us to
address, or require any further assistance, please let us know.

Regards.....

Praveen (SYSTEMS)



A-8, Sector- 63, Noida, UP

Email:  ***@***.***> ***@***.***

website:  <http://www.isgec.com> www.isgec.com

Mobile:  +91 8448595785

 

From: saravanan  ***@***.***>
***@***.*** 
Sent: 18 January 2021 17:15
To: 'Praveen Kumar'
Cc:  ***@***.***> ***@***.***
Subject: Access (Read & write) required for civil project folder

 

Dear sir,

 

Please provide me the Access (Read & write ) for "Civil projects" folder. 

 

Regards,

 

SARAVANAN 

EPC ENGG. (CIVIL) 



Grace building, No.25, Mc Nichols Road, Chetpet,

Chennai - 600 031, India

Mobile: +91-9003336388

E-mail:  ***@***.***>
***@***.***
