### ISSUE TITLE
Data Folder Access to Mr. Aayushman Chauhan (3902)

### ISSUE THREAD

**Issue by praveen-isgec** [Isgec/ITIL-FileServer-Permissions#11]
Dear Praveen,

I request you to please give access for my data folder on server to Aayushman Chauhan Emp. ID – 3902, he is working in my team and need to work on common enquiries. 
My employee code is 1856

Regards,
Pankaj Sharma
International Marketing
@Isgec/dc-infra-team   ,Myself Praveen Kumar is working for the same.

**Comment by msrawat-isgec** [comment]
From: praveen-isgec ***@***.*** 
Sent: 19 March 2021 14:14
To: Isgec/ITIL-FileServer-Permissions
Cc: M. S. Rawat; Team mention
Subject: [Isgec/ITIL-FileServer-Permissions] Data Folder Access to Mr. Aayushman Chauhan (3902) (#11)

 

Dear Praveen,

I request you to please give access for my data folder on server to Aayushman Chauhan Emp. ID – 3902, he is working in my team and need to work on common enquiries.
My employee code is 1856

Regards,
Pankaj Sharma
International Marketing
@Isgec/dc-infra-team <https://github.com/orgs/Isgec/teams/dc-infra-team>  ,Myself Praveen Kumar is working for the same.

**Comment by praveen-isgec** [comment]
Needful  is done. Full access rights is given to Mr. Aayushman (3902) on Mr. Pankaj(1856) forlder as per request by Mr. Pankah Sharma.
