### ISSUE TITLE
 Access request for EPC E&I team memebers - Reg (PROPOSAL ISO DRIVE)

### ISSUE THREAD

**Issue by praveen-isgec** [Isgec/ITIL-FileServer-Permissions#13]
Sl. No | Name | Staff Number | Department | Remarks
-- | -- | -- | -- | --
  | Vadivel .V.M | 2148 | EPC Proposal -   Electrical | Both Read and   Write access
  | Rajasekaran .G | 2822 | EPC Proposal -   Electrical | Both Read and   Write access
  | Maheshkumar .M | 3534 | EPC Proposal -   Electrical | Both Read and   Write access
  | Hema varama   gopinath | 3811 | EPC Proposal –   C&I | Both Read and   Write access
  | Murugan .P | 3671 | EPC Proposal –   C&I | Both Read and Write   access

@Isgec/dc-infra-team  , Myself Praveen Kumar is working for the same.

**Comment by praveen-isgec** [comment]
Folder Link : 
Kindly provide access to below specified EPC E&I team members for our proposal ISO folder.
\\192.168.22.5\proposal iso
Do the needful.
From: Praveen Kumar <praveen1.kumar@isgec.co.in> 
Sent: 12 April 2021 16:58
To: 'VADIVEL' <vadivel.vm@isgec.co.in>
Cc: 'helpdesk.chennai@isgec.co.in' <helpdesk.chennai@isgec.co.in>; 'ARUN RAJ R' <arunraj.r@isgec.co.in>; 'Muthu' <muthu@isgec.co.in>; 'e.adhimoolam@isgec.co.in' <e.adhimoolam@isgec.co.in>; 'Rajasekaran.G' <g.rajasekaran@isgec.co.in>; 'm.maheshkumar@isgec.co.in' <m.maheshkumar@isgec.co.in>; 'hemavarmagopinath@isgec.co.in' <hemavarmagopinath@isgec.co.in>; 'murugan' <murugan.p@isgec.co.in>
Subject: RE: Access request for EPC E&I team memebers - Reg

Hello Mr. Vadivel,

Needful is done. Path details as follows.

\\192.168.22.5\PROPOSAL ISO

Advice to all mentioned users that if not able to access please take restart of them system for reflect permissions immediately or call to concerned helpdesk team if require any assistance.

@Helpdesk Team, Please map mentioned drive on given user’s machines.

@dhirendra-isgec   ,DSB Please close this call.

**Comment by dhirendra-isgec** [comment]
Case closed
