### ISSUE TITLE
\\192.168.22.5\ijtautomatio_dwgcount - Full Access to Boiler Chennai Users.

### ISSUE THREAD

**Issue by praveen-isgec** [Isgec/ITIL-FileServer-Permissions#4]
Mr. K Arunkumar send request for access  read  and write access for Chennai user following folder on below mentioned path \\192.168.22.5\ijtautomatio_dwgcount

1 | V. Kavaskar | 3497
-- | -- | --
2 | R. Rajesh | 3468
3 | D. Sathish kumar | 1310
4 | S. Chandrasekar | 1134
5 | J. Sudhakar | 1308
6 | M. Rajesh Kumar | 1202
7 | V. Balan | 10582
8 | G. Subash chandran | 3559
9 | S. Vignesh | 3759
10 | S. Bharathiraja | 3758
11 | K. Bharathiraja | 3764
12 | P. Thangaraj | 3659
13 | R. Prakash | 10412
14 | Sampath kumar | 20052
15 | S. Karthik | 20035
16 | Aravindhan V | 20049
17 | Pandi selvam | 20071

@Isgec/dc-infra-team   , Myself Praveen Kumar is working same.

**Comment by msrawat-isgec** [comment]
FYI
