### ISSUE TITLE
SS0148_INTERNAL SHARE DRIVE FOR KPR PROJECT

### ISSUE THREAD

**Issue by praveen-isgec** [Isgec/ITIL-FileServer-Permissions#5]
Kindly allot one shared drive for KPR Project (SS0148) which we are going to use for Internal Project coordination between Project, Design, Quality and Commercial. 
 
Access for the same shall be granted by following Project Team Members.
 
1.	Neeraj Agarwal
2.	Love Sharma
3.	Munish Gupta
 
Cc: VG Sir: Pl. accord your approval. 
 
Regards,
Munish Gupta
Deputy Manager (SMD Contracts) 
@Isgec/dc-infra-team  , Myself Praveen Kumar is working for the same.

**Comment by msrawat-isgec** [comment]
FYI

**Comment by msrawat-isgec** [comment]
Dear Mr. Munish,

 

Share drives is created as per given details. Please find the path.

 

\\192.9.200.161\SMDPROJECTS <file:///\\192.9.200.161\SMDPROJECTS> 

 

Full access rights are given to all below mentioned users.

 

Please try to access if not able to access then take restart of your systems for replicate permissions immediately or call to concerned helpdesk team if required any assistance.

 

@Helpdesk Team, please map mentioned drive in all given user’s machines.

 

 

If you have any additional questions or concerns you would like us to address, or require any further assistance, please let us know.

Regards.....

Praveen (SYSTEMS)

cid:image002.png@01D5CC89.FCA7D120

A-8, Sector- 63, Noida, UP

Email: praveen1.kumar@isgec.co.in

website: www.isgec.com

Mobile:  +91 8448595785

 

From: Munish Gupta [mailto:munish.gupta@isgec.co.in] 
Sent: 18 February 2021 15:36
To: 'Praveen Kumar'; 'Helpdesk'
Cc: Vikas.gandhi@isgec.co.in; 'neeraj agarwal'; love.sharma@isgec.co.in; 'Vikas Gandhi'
Subject: RE: SS0148_INTERNAL SHARE DRIVE FOR KPR PROJECT

 

Dear IT Team,

 

Pl. confirm the status. 

 

Regards,

Munish Gupta

Deputy Manager (SMD Contracts)

Description: Description: Description: Description: Description: Description: Description: Description: Description: Description: cid:image001.png@01D46C5E.994C5830

A-4, Sector 24, Noida – 201 301 

Uttar Pradesh, India

Tel: +91-120 - 408 5274

Mob. : +91- 9899180065

Email:  <mailto:munish.gupta@isgec.co.in> munish.gupta@isgec.co.in

 

From: Vikas Gandhi [mailto:vikasgandhi@isgec.co.in] 
Sent: Wednesday, February 17, 2021 11:41 AM
To: Munish Gupta
Cc: Helpdesk; Praveen Kumar; Vikas.gandhi@isgec.co.in; neeraj agarwal; love.sharma@isgec.co.in
Subject: Re: SS0148_INTERNAL SHARE DRIVE FOR KPR PROJECT

 

Ok

Sent from my iPhone

 

On 17-Feb-2021, at 10:10 AM, Munish Gupta <munish.gupta@isgec.co.in> wrote:

﻿

Dear Helpdesk Team,

 

Kindly allot one shared drive for KPR Project (SS0148) which we are going to use for Internal Project coordination between Project, Design, Quality and Commercial. 

 

Access for the same shall be granted by following Project Team Members.

 

1.       Neeraj Agarwal

2.       Love Sharma

3.       Munish Gupta

 

Cc: VG Sir: Pl. accord your approval. 

 

Regards,

Munish Gupta

Deputy Manager (SMD Contracts) 

<image001.png>

A-4, Sector 24, Noida – 201 301 

Uttar Pradesh, India

Tel: +91-120 - 408 5274

Mob. : +91- 9899180065

Email:  <mailto:munish.gupta@isgec.co.in> munish.gupta@isgec.co.in

**Comment by msrawat-isgec** [comment]
Dear Praveen, 

 

We have define the access to be provided on the shared drive for KPR (SS0148) as per enclosed excel. 

 

Kindly allot to every team member as defined in the attached excel and also link them with the shared drive. 

 

Regards,

Munish Gupta

Deputy Manager (SMD Contracts)

Description: Description: Description: Description: Description: Description: Description: Description: Description: Description: cid:image001.png@01D46C5E.994C5830

A-4, Sector 24, Noida – 201 301 

Uttar Pradesh, India

Tel: +91-120 - 408 5274

Mob. : +91- 9899180065

Email:  <mailto:munish.gupta@isgec.co.in> munish.gupta@isgec.co.in

 

From: Praveen Kumar [mailto:praveen1.kumar@isgec.co.in] 
Sent: Friday, February 19, 2021 5:19 PM
To: 'Munish Gupta'
Cc: Vikas.gandhi@isgec.co.in; 'neeraj agarwal'; love.sharma@isgec.co.in; 'Vikas Gandhi'; 'Helpdesk'; reply@reply.github.com; 'Dhirendra Singh Bisht'; 'Vinay Sharma'
Subject: RE: SS0148_INTERNAL SHARE DRIVE FOR KPR PROJECT

 

Dear Mr. Munish,

 

Share drives is created as per given details. Please find the path.

 

\\192.9.200.161\SMDPROJECTS <file:///\\192.9.200.161\SMDPROJECTS> 

 

Full access rights are given to all below mentioned users.

 

Please try to access if not able to access then take restart of your systems for replicate permissions immediately or call to concerned helpdesk team if required any assistance.

 

@Helpdesk Team, please map mentioned drive in all given user’s machines.

 

 

If you have any additional questions or concerns you would like us to address, or require any further assistance, please let us know.

Regards.....

Praveen (SYSTEMS)

cid:image002.png@01D5CC89.FCA7D120

A-8, Sector- 63, Noida, UP

Email: praveen1.kumar@isgec.co.in

website: www.isgec.com

Mobile:  +91 8448595785

 

From: Munish Gupta [mailto:munish.gupta@isgec.co.in] 
Sent: 18 February 2021 15:36
To: 'Praveen Kumar'; 'Helpdesk'
Cc: Vikas.gandhi@isgec.co.in; 'neeraj agarwal'; love.sharma@isgec.co.in; 'Vikas Gandhi'
Subject: RE: SS0148_INTERNAL SHARE DRIVE FOR KPR PROJECT

 

Dear IT Team,

 

Pl. confirm the status. 

 

Regards,

Munish Gupta

Deputy Manager (SMD Contracts)

Description: Description: Description: Description: Description: Description: Description: Description: Description: Description: cid:image001.png@01D46C5E.994C5830

A-4, Sector 24, Noida – 201 301 

Uttar Pradesh, India

Tel: +91-120 - 408 5274

Mob. : +91- 9899180065

Email:  <mailto:munish.gupta@isgec.co.in> munish.gupta@isgec.co.in

 

From: Vikas Gandhi [mailto:vikasgandhi@isgec.co.in] 
Sent: Wednesday, February 17, 2021 11:41 AM
To: Munish Gupta
Cc: Helpdesk; Praveen Kumar; Vikas.gandhi@isgec.co.in; neeraj agarwal; love.sharma@isgec.co.in
Subject: Re: SS0148_INTERNAL SHARE DRIVE FOR KPR PROJECT

 

Ok

Sent from my iPhone

 

On 17-Feb-2021, at 10:10 AM, Munish Gupta <munish.gupta@isgec.co.in> wrote:

﻿

Dear Helpdesk Team,

 

Kindly allot one shared drive for KPR Project (SS0148) which we are going to use for Internal Project coordination between Project, Design, Quality and Commercial. 

 

Access for the same shall be granted by following Project Team Members.

 

1.       Neeraj Agarwal

2.       Love Sharma

3.       Munish Gupta

 

Cc: VG Sir: Pl. accord your approval. 

 

Regards,

Munish Gupta

Deputy Manager (SMD Contracts) 

<image001.png>

A-4, Sector 24, Noida – 201 301 

Uttar Pradesh, India

Tel: +91-120 - 408 5274

Mob. : +91- 9899180065

Email:  <mailto:munish.gupta@isgec.co.in> munish.gupta@isgec.co.in

**Comment by msrawat-isgec** [comment]
Gentle Reminder….

 

Dear Praveen Ji,

 

We would like to know the current status of trialing request as we need to start the activities on priority basis.

 

Hope, the access for all the members will be assigned by today.

 

Waiting for your prompt response. 

 

Regards,

Munish Gupta

Deputy Manager (SMD Contracts)

Description: Description: Description: Description: Description: Description: Description: Description: Description: Description: cid:image001.png@01D46C5E.994C5830

A-4, Sector 24, Noida – 201 301 

Uttar Pradesh, India

Tel: +91-120 - 408 5274

Mob. : +91- 9899180065

Email:  <mailto:munish.gupta@isgec.co.in> munish.gupta@isgec.co.in

 

From: Munish Gupta [mailto:munish.gupta@isgec.co.in] 
Sent: Monday, March 1, 2021 5:31 PM
To: 'Praveen Kumar'
Cc: 'Vikas.gandhi@isgec.co.in'; 'neeraj agarwal'; 'love.sharma@isgec.co.in'; 'Vikas Gandhi'; 'Helpdesk'; 'reply@reply.github.com'; 'Dhirendra Singh Bisht'; 'Vinay Sharma'; 'kprsugar@isgec.co.in'
Subject: RE: SS0148_INTERNAL SHARE DRIVE FOR KPR PROJECT

 

Dear Praveen, 

 

We have define the access to be provided on the shared drive for KPR (SS0148) as per enclosed excel. 

 

Kindly allot to every team member as defined in the attached excel and also link them with the shared drive. 

 

Regards,

Munish Gupta

Deputy Manager (SMD Contracts)

Description: Description: Description: Description: Description: Description: Description: Description: Description: Description: cid:image001.png@01D46C5E.994C5830

A-4, Sector 24, Noida – 201 301 

Uttar Pradesh, India

Tel: +91-120 - 408 5274

Mob. : +91- 9899180065

Email:  <mailto:munish.gupta@isgec.co.in> munish.gupta@isgec.co.in

 

From: Praveen Kumar [mailto:praveen1.kumar@isgec.co.in] 
Sent: Friday, February 19, 2021 5:19 PM
To: 'Munish Gupta'
Cc: Vikas.gandhi@isgec.co.in; 'neeraj agarwal'; love.sharma@isgec.co.in; 'Vikas Gandhi'; 'Helpdesk'; reply@reply.github.com; 'Dhirendra Singh Bisht'; 'Vinay Sharma'
Subject: RE: SS0148_INTERNAL SHARE DRIVE FOR KPR PROJECT

 

Dear Mr. Munish,

 

Share drives is created as per given details. Please find the path.

 

\\192.9.200.161\SMDPROJECTS <file:///\\192.9.200.161\SMDPROJECTS> 

 

Full access rights are given to all below mentioned users.

 

Please try to access if not able to access then take restart of your systems for replicate permissions immediately or call to concerned helpdesk team if required any assistance.

 

@Helpdesk Team, please map mentioned drive in all given user’s machines.

 

 

If you have any additional questions or concerns you would like us to address, or require any further assistance, please let us know.

Regards.....

Praveen (SYSTEMS)

cid:image002.png@01D5CC89.FCA7D120

A-8, Sector- 63, Noida, UP

Email: praveen1.kumar@isgec.co.in

website: www.isgec.com

Mobile:  +91 8448595785

 

From: Munish Gupta [mailto:munish.gupta@isgec.co.in] 
Sent: 18 February 2021 15:36
To: 'Praveen Kumar'; 'Helpdesk'
Cc: Vikas.gandhi@isgec.co.in; 'neeraj agarwal'; love.sharma@isgec.co.in; 'Vikas Gandhi'
Subject: RE: SS0148_INTERNAL SHARE DRIVE FOR KPR PROJECT

 

Dear IT Team,

 

Pl. confirm the status. 

 

Regards,

Munish Gupta

Deputy Manager (SMD Contracts)

Description: Description: Description: Description: Description: Description: Description: Description: Description: Description: cid:image001.png@01D46C5E.994C5830

A-4, Sector 24, Noida – 201 301 

Uttar Pradesh, India

Tel: +91-120 - 408 5274

Mob. : +91- 9899180065

Email:  <mailto:munish.gupta@isgec.co.in> munish.gupta@isgec.co.in

 

From: Vikas Gandhi [mailto:vikasgandhi@isgec.co.in] 
Sent: Wednesday, February 17, 2021 11:41 AM
To: Munish Gupta
Cc: Helpdesk; Praveen Kumar; Vikas.gandhi@isgec.co.in; neeraj agarwal; love.sharma@isgec.co.in
Subject: Re: SS0148_INTERNAL SHARE DRIVE FOR KPR PROJECT

 

Ok

Sent from my iPhone

 

On 17-Feb-2021, at 10:10 AM, Munish Gupta <munish.gupta@isgec.co.in> wrote:

﻿

Dear Helpdesk Team,

 

Kindly allot one shared drive for KPR Project (SS0148) which we are going to use for Internal Project coordination between Project, Design, Quality and Commercial. 

 

Access for the same shall be granted by following Project Team Members.

 

1.       Neeraj Agarwal

2.       Love Sharma

3.       Munish Gupta

 

Cc: VG Sir: Pl. accord your approval. 

 

Regards,

Munish Gupta

Deputy Manager (SMD Contracts) 

<image001.png>

A-4, Sector 24, Noida – 201 301 

Uttar Pradesh, India

Tel: +91-120 - 408 5274

Mob. : +91- 9899180065

Email:  <mailto:munish.gupta@isgec.co.in> munish.gupta@isgec.co.in

**Comment by msrawat-isgec** [comment]
Dear Mr. Munish,

 

Needful is done. 

 

Advice to all mentioned users, please take restart of your system for reflect permissions immediately or call to concerned helpdesk team if require any assistance.

 

Access rights are given as per given details, Path details as follows.

 

\\192.9.200.161\SMDPROJECTS <file:///\\192.9.200.161\SMDPROJECTS> 



 

If you have any additional questions or concerns you would like us to address, or require any further assistance, please let us know.

Regards.....

Praveen (SYSTEMS)

***@***.***D5CC89.FCA7D120

A-8, Sector- 63, Noida, UP

Email: ***@***.***

website: www.isgec.com

Mobile:  +91 8448595785

 

From: Munish Gupta ***@***.*** 
Sent: 09 March 2021 10:17
To: 'Praveen Kumar'
Cc: ***@***.***; 'neeraj agarwal'; ***@***.***; 'Vikas Gandhi'; 'Helpdesk'; ***@***.***; 'Dhirendra Singh Bisht'; 'Vinay Sharma'; ***@***.***
Subject: RE: SS0148_INTERNAL SHARE DRIVE FOR KPR PROJECT

 

Reminder 2…

 

Dear Praveen Ji,

 

We are awaiting for your response. Project is alive and we need to start to use sharing source for data storage and coordination. 

 

Regards,

Munish Gupta

Deputy Manager (SMD Contracts)

Description: Description: Description: Description: Description: Description: Description: Description: Description: Description: ***@***.***D46C5E.994C5830

A-4, Sector 24, Noida – 201 301 

Uttar Pradesh, India

Tel: +91-120 - 408 5274

Mob. : +91- 9899180065

Email:  ***@***.***> ***@***.***

 

From: Munish Gupta ***@***.*** 
Sent: Friday, March 5, 2021 11:52 AM
To: 'Praveen Kumar'
Cc: ***@***.***'; 'neeraj agarwal'; ***@***.***'; 'Vikas Gandhi'; 'Helpdesk'; ***@***.***'; 'Dhirendra Singh Bisht'; 'Vinay Sharma'; ***@***.***'
Subject: RE: SS0148_INTERNAL SHARE DRIVE FOR KPR PROJECT

 

Gentle Reminder….

 

Dear Praveen Ji,

 

We would like to know the current status of trialing request as we need to start the activities on priority basis.

 

Hope, the access for all the members will be assigned by today.

 

Waiting for your prompt response. 

 

Regards,

Munish Gupta

Deputy Manager (SMD Contracts)

Description: Description: Description: Description: Description: Description: Description: Description: Description: Description: ***@***.***D46C5E.994C5830

A-4, Sector 24, Noida – 201 301 

Uttar Pradesh, India

Tel: +91-120 - 408 5274

Mob. : +91- 9899180065

Email:  ***@***.***> ***@***.***

 

From: Munish Gupta ***@***.*** 
Sent: Monday, March 1, 2021 5:31 PM
To: 'Praveen Kumar'
Cc: ***@***.***'; 'neeraj agarwal'; ***@***.***'; 'Vikas Gandhi'; 'Helpdesk'; ***@***.***'; 'Dhirendra Singh Bisht'; 'Vinay Sharma'; ***@***.***'
Subject: RE: SS0148_INTERNAL SHARE DRIVE FOR KPR PROJECT

 

Dear Praveen, 

 

We have define the access to be provided on the shared drive for KPR (SS0148) as per enclosed excel. 

 

Kindly allot to every team member as defined in the attached excel and also link them with the shared drive. 

 

Regards,

Munish Gupta

Deputy Manager (SMD Contracts)

Description: Description: Description: Description: Description: Description: Description: Description: Description: Description: ***@***.***D46C5E.994C5830

A-4, Sector 24, Noida – 201 301 

Uttar Pradesh, India

Tel: +91-120 - 408 5274

Mob. : +91- 9899180065

Email:  ***@***.***> ***@***.***

 

From: Praveen Kumar ***@***.*** 
Sent: Friday, February 19, 2021 5:19 PM
To: 'Munish Gupta'
Cc: ***@***.***; 'neeraj agarwal'; ***@***.***; 'Vikas Gandhi'; 'Helpdesk'; ***@***.***; 'Dhirendra Singh Bisht'; 'Vinay Sharma'
Subject: RE: SS0148_INTERNAL SHARE DRIVE FOR KPR PROJECT

 

Dear Mr. Munish,

 

Share drives is created as per given details. Please find the path.

 

\\192.9.200.161\SMDPROJECTS <file:///\\192.9.200.161\SMDPROJECTS> 

 

Full access rights are given to all below mentioned users.

 

Please try to access if not able to access then take restart of your systems for replicate permissions immediately or call to concerned helpdesk team if required any assistance.

 

@Helpdesk Team, please map mentioned drive in all given user’s machines.

 

 

If you have any additional questions or concerns you would like us to address, or require any further assistance, please let us know.

Regards.....

Praveen (SYSTEMS)

***@***.***D5CC89.FCA7D120

A-8, Sector- 63, Noida, UP

Email: ***@***.***

website: www.isgec.com

Mobile:  +91 8448595785

 

From: Munish Gupta ***@***.*** 
Sent: 18 February 2021 15:36
To: 'Praveen Kumar'; 'Helpdesk'
Cc: ***@***.***; 'neeraj agarwal'; ***@***.***; 'Vikas Gandhi'
Subject: RE: SS0148_INTERNAL SHARE DRIVE FOR KPR PROJECT

 

Dear IT Team,

 

Pl. confirm the status. 

 

Regards,

Munish Gupta

Deputy Manager (SMD Contracts)

Description: Description: Description: Description: Description: Description: Description: Description: Description: Description: ***@***.***D46C5E.994C5830

A-4, Sector 24, Noida – 201 301 

Uttar Pradesh, India

Tel: +91-120 - 408 5274

Mob. : +91- 9899180065

Email:  ***@***.***> ***@***.***

 

From: Vikas Gandhi ***@***.*** 
Sent: Wednesday, February 17, 2021 11:41 AM
To: Munish Gupta
Cc: Helpdesk; Praveen Kumar; ***@***.***; neeraj agarwal; ***@***.***
Subject: Re: SS0148_INTERNAL SHARE DRIVE FOR KPR PROJECT

 

Ok

Sent from my iPhone

 

On 17-Feb-2021, at 10:10 AM, Munish Gupta ***@***.***> wrote:

﻿

Dear Helpdesk Team,

 

Kindly allot one shared drive for KPR Project (SS0148) which we are going to use for Internal Project coordination between Project, Design, Quality and Commercial. 

 

Access for the same shall be granted by following Project Team Members.

 

1.       Neeraj Agarwal

2.       Love Sharma

3.       Munish Gupta

 

Cc: VG Sir: Pl. accord your approval. 

 

Regards,

Munish Gupta

Deputy Manager (SMD Contracts) 

<image001.png>

A-4, Sector 24, Noida – 201 301 

Uttar Pradesh, India

Tel: +91-120 - 408 5274

Mob. : +91- 9899180065

Email:  ***@***.***> ***@***.***

**Comment by msrawat-isgec** [comment]
Dear Praveen Ji,

 

Some additional access are need to be provided as per trailing information. 

 

1.       Access to be granted for Dispatch Info Folder.

2.       Additional Access need to be granted to Mr. Alok Sehgal, Mr. Dinesh Kumar, Mr. P Mahto and Mr. Praveen Kumar. Information updated in the attached file.

 

Kindly do the needful. 

 

Regards,

Munish Gupta

Deputy Manager (SMD Contracts)

Description: Description: Description: Description: Description: Description: Description: Description: Description: Description: ***@***.***D46C5E.994C5830

A-4, Sector 24, Noida – 201 301 

Uttar Pradesh, India

Tel: +91-120 - 408 5274

Mob. : +91- 9899180065

Email:  ***@***.***> ***@***.***

 

From: Praveen Kumar ***@***.*** 
Sent: Thursday, March 11, 2021 3:56 PM
To: 'Munish Gupta'
Cc: ***@***.***; 'neeraj agarwal'; ***@***.***; 'Vikas Gandhi'; 'Helpdesk'; ***@***.***; 'Dhirendra Singh Bisht'; 'Vinay Sharma'; ***@***.***
Subject: RE: SS0148_INTERNAL SHARE DRIVE FOR KPR PROJECT

 

Dear Mr. Munish,

 

Needful is done. 

 

Advice to all mentioned users, please take restart of your system for reflect permissions immediately or call to concerned helpdesk team if require any assistance.

 

Access rights are given as per given details, Path details as follows.

 

\\192.9.200.161\SMDPROJECTS <file:///\\192.9.200.161\SMDPROJECTS> 



 

If you have any additional questions or concerns you would like us to address, or require any further assistance, please let us know.

Regards.....

Praveen (SYSTEMS)

***@***.***D5CC89.FCA7D120

A-8, Sector- 63, Noida, UP

Email: ***@***.***

website: www.isgec.com

Mobile:  +91 8448595785

 

From: Munish Gupta ***@***.*** 
Sent: 09 March 2021 10:17
To: 'Praveen Kumar'
Cc: ***@***.***; 'neeraj agarwal'; ***@***.***; 'Vikas Gandhi'; 'Helpdesk'; ***@***.***; 'Dhirendra Singh Bisht'; 'Vinay Sharma'; ***@***.***
Subject: RE: SS0148_INTERNAL SHARE DRIVE FOR KPR PROJECT

 

Reminder 2…

 

Dear Praveen Ji,

 

We are awaiting for your response. Project is alive and we need to start to use sharing source for data storage and coordination. 

 

Regards,

Munish Gupta

Deputy Manager (SMD Contracts)

Description: Description: Description: Description: Description: Description: Description: Description: Description: Description: ***@***.***D46C5E.994C5830

A-4, Sector 24, Noida – 201 301 

Uttar Pradesh, India

Tel: +91-120 - 408 5274

Mob. : +91- 9899180065

Email:  ***@***.***> ***@***.***

 

From: Munish Gupta ***@***.*** 
Sent: Friday, March 5, 2021 11:52 AM
To: 'Praveen Kumar'
Cc: ***@***.***'; 'neeraj agarwal'; ***@***.***'; 'Vikas Gandhi'; 'Helpdesk'; ***@***.***'; 'Dhirendra Singh Bisht'; 'Vinay Sharma'; ***@***.***'
Subject: RE: SS0148_INTERNAL SHARE DRIVE FOR KPR PROJECT

 

Gentle Reminder….

 

Dear Praveen Ji,

 

We would like to know the current status of trialing request as we need to start the activities on priority basis.

 

Hope, the access for all the members will be assigned by today.

 

Waiting for your prompt response. 

 

Regards,

Munish Gupta

Deputy Manager (SMD Contracts)

Description: Description: Description: Description: Description: Description: Description: Description: Description: Description: ***@***.***D46C5E.994C5830

A-4, Sector 24, Noida – 201 301 

Uttar Pradesh, India

Tel: +91-120 - 408 5274

Mob. : +91- 9899180065

Email:  ***@***.***> ***@***.***

 

From: Munish Gupta ***@***.*** 
Sent: Monday, March 1, 2021 5:31 PM
To: 'Praveen Kumar'
Cc: ***@***.***'; 'neeraj agarwal'; ***@***.***'; 'Vikas Gandhi'; 'Helpdesk'; ***@***.***'; 'Dhirendra Singh Bisht'; 'Vinay Sharma'; ***@***.***'
Subject: RE: SS0148_INTERNAL SHARE DRIVE FOR KPR PROJECT

 

Dear Praveen, 

 

We have define the access to be provided on the shared drive for KPR (SS0148) as per enclosed excel. 

 

Kindly allot to every team member as defined in the attached excel and also link them with the shared drive. 

 

Regards,

Munish Gupta

Deputy Manager (SMD Contracts)

Description: Description: Description: Description: Description: Description: Description: Description: Description: Description: ***@***.***D46C5E.994C5830

A-4, Sector 24, Noida – 201 301 

Uttar Pradesh, India

Tel: +91-120 - 408 5274

Mob. : +91- 9899180065

Email:  ***@***.***> ***@***.***

 

From: Praveen Kumar ***@***.*** 
Sent: Friday, February 19, 2021 5:19 PM
To: 'Munish Gupta'
Cc: ***@***.***; 'neeraj agarwal'; ***@***.***; 'Vikas Gandhi'; 'Helpdesk'; ***@***.***; 'Dhirendra Singh Bisht'; 'Vinay Sharma'
Subject: RE: SS0148_INTERNAL SHARE DRIVE FOR KPR PROJECT

 

Dear Mr. Munish,

 

Share drives is created as per given details. Please find the path.

 

\\192.9.200.161\SMDPROJECTS <file:///\\192.9.200.161\SMDPROJECTS> 

 

Full access rights are given to all below mentioned users.

 

Please try to access if not able to access then take restart of your systems for replicate permissions immediately or call to concerned helpdesk team if required any assistance.

 

@Helpdesk Team, please map mentioned drive in all given user’s machines.

 

 

If you have any additional questions or concerns you would like us to address, or require any further assistance, please let us know.

Regards.....

Praveen (SYSTEMS)

***@***.***D5CC89.FCA7D120

A-8, Sector- 63, Noida, UP

Email: ***@***.***

website: www.isgec.com

Mobile:  +91 8448595785

 

From: Munish Gupta ***@***.*** 
Sent: 18 February 2021 15:36
To: 'Praveen Kumar'; 'Helpdesk'
Cc: ***@***.***; 'neeraj agarwal'; ***@***.***; 'Vikas Gandhi'
Subject: RE: SS0148_INTERNAL SHARE DRIVE FOR KPR PROJECT

 

Dear IT Team,

 

Pl. confirm the status. 

 

Regards,

Munish Gupta

Deputy Manager (SMD Contracts)

Description: Description: Description: Description: Description: Description: Description: Description: Description: Description: ***@***.***D46C5E.994C5830

A-4, Sector 24, Noida – 201 301 

Uttar Pradesh, India

Tel: +91-120 - 408 5274

Mob. : +91- 9899180065

Email:  ***@***.***> ***@***.***

 

From: Vikas Gandhi ***@***.*** 
Sent: Wednesday, February 17, 2021 11:41 AM
To: Munish Gupta
Cc: Helpdesk; Praveen Kumar; ***@***.***; neeraj agarwal; ***@***.***
Subject: Re: SS0148_INTERNAL SHARE DRIVE FOR KPR PROJECT

 

Ok

Sent from my iPhone

 

On 17-Feb-2021, at 10:10 AM, Munish Gupta ***@***.***> wrote:

﻿

Dear Helpdesk Team,

 

Kindly allot one shared drive for KPR Project (SS0148) which we are going to use for Internal Project coordination between Project, Design, Quality and Commercial. 

 

Access for the same shall be granted by following Project Team Members.

 

1.       Neeraj Agarwal

2.       Love Sharma

3.       Munish Gupta

 

Cc: VG Sir: Pl. accord your approval. 

 

Regards,

Munish Gupta

Deputy Manager (SMD Contracts) 

<image001.png>

A-4, Sector 24, Noida – 201 301 

Uttar Pradesh, India

Tel: +91-120 - 408 5274

Mob. : +91- 9899180065

Email:  ***@***.***> ***@***.***
