### ISSUE TITLE
Domain updation - System - R.Balasubramanian (Assigned Common workstation to Mr. R Balasubramanian- Chennai)

### ISSUE THREAD

**Issue by praveen-isgec** [Isgec/ITIL-FileServer-Permissions#6]
Refer our today discussion, please change the Computer name currently(Cadison) being used by R.Balasubramanian to match his employee code to ensure Prohance software installation. 

I attach the screen shot of system for your furtherance.

Mr.Praveen : Pl. do the needful.

--
Regards,
 
Velmurugan.R.M

@Isgec/dc-infra-team  , Myself Praven Kumar is working for the same.

**Comment by msrawat-isgec** [comment]
FYI
